### ISSUE TITLE
[통계] 관리자는 매출액 순위를 조회할 수 있습니다.

### ISSUE THREAD

**Issue by i-Veni-Vidi-Vici** [ssg-java3-240304/shop-Furni-Dream#27]
## 🌈 Success criteria 

1. [월/분기]
2. [전체/카테고리]

## 👷To-do

- [ ]  월간 전체 매출액 순위 조회
- [ ]  분기 전체 매출액 순위 조회
- [ ]  월간 카테고리별 매출액 순위 조회
- [ ]  분기 카테고리별 매출액 순위 조회
