### ISSUE TITLE
관리자는 기간별로 매출을 조회할 수 있습니다.

### ISSUE THREAD

**Issue by Hong-ji-min** [ssg-java3-240304/shop-Furni-Dream#5]
## 🍒 To-do

- [x] 일별로 매출 조회를 할 수 있습니다.
- [x] 월별 매출 조회를 할 수 있습니다.
- [x] 분기별 매출 조회를 할 수 있습니다.

### 🌟전체 매출 조회 testcode 성공
![image](https://github.com/ssg-java3-240304/shop-Furni-Dream/assets/80135858/af364a47-228c-41b5-8912-0c42fa1719a5)

### 🌟월별 매출 조회 testcode 성공
![image](https://github.com/ssg-java3-240304/shop-Furni-Dream/assets/80135858/9a251045-8e5c-4bb8-afca-f3d2c74920d1)

### 🌟분기별 매출 조회 testcode 성공
![image](https://github.com/ssg-java3-240304/shop-Furni-Dream/assets/80135858/122a36b3-7d1f-4231-8f23-548c7f16ac47)

**Comment by Hong-ji-min** [comment]
## 🌟전체 매출 조회 testcode 성공
![image](https://github.com/ssg-java3-240304/shop-Furni-Dream/assets/80135858/af364a47-228c-41b5-8912-0c42fa1719a5)



## 🌟월별 매출 조회 testcode 성공
![image](https://github.com/ssg-java3-240304/shop-Furni-Dream/assets/80135858/9a251045-8e5c-4bb8-afca-f3d2c74920d1)
