### ISSUE TITLE
관리자는 전체 주문 리스트를 조회할 수 있습니다

### ISSUE THREAD

**Issue by CstoneKu** [ssg-java3-240304/shop-Furni-Dream#9]
## 🌈 Success criteria 
1. 관리자는 주문 전체 리스트를 조회할 수 있습니다.
2. 전체 주문 조회 DAO Test 코드 작성 하기
3. 주문 조회 서비스 전체 주문 조회 기능 작성 하기

## 👷To-do
- [x] #35
- [x] 전체 주문 조회 DAO Test 코드 작성 하기
- [x] 주문 조회 서비스 전체 주문 조회 기능 작성 하기
- [x] 전체 주문 조회 페이지 작성 하기
- [x] Enum 설정
